In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_rows", 100)
#pd.set_option('display.max_columns', 100)
pd.set_option('display.expand_frame_repr', False)

In [2]:
survey = pd.read_csv('survey.csv')
survey

                Timestamp  Age  Gender         Country state self_employed family_history treatment work_interfere    no_employees  ...               leave mental_health_consequence phys_health_consequence     coworkers    supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence comments
0     2014-08-27 11:29:31   37  Female   United States    IL           NaN             No       Yes          Often            6-25  ...       Somewhat easy                        No                      No  Some of them           Yes                      No                 Maybe                Yes              No      NaN
1     2014-08-27 11:29:37   44       M   United States    IN           NaN             No        No         Rarely  More than 1000  ...          Don't know                     Maybe                      No            No            No                      No                    No         Don't know              No      NaN
2     2014-08-27 11:29:44   32    Male          Canada   NaN           NaN             No        No         Rarely            6-25  ...  Somewhat difficult                        No                      No           Yes           Yes                     Yes                   Yes                 No              No      NaN
3     2014-08-27 11:29:46   31    Male  United Kingdom   NaN           NaN            Yes       Yes          Often          26-100  ...  Somewhat difficult                       Yes                     Yes  Some of them            No                   Maybe                 Maybe                 No             Yes      NaN
4     2014-08-27 11:30:22   31    Male   United States    TX           NaN             No        No          Never         100-500  ...          Don't know                        No                      No  Some of them           Yes                     Yes                   Yes         Don't know              No      NaN
...                   ...  ...     ...             ...   ...           ...            ...       ...            ...             ...  ...                 ...                       ...                     ...           ...           ...                     ...                   ...                ...             ...      ...
1254  2015-09-12 11:17:21   26    male  United Kingdom   NaN            No             No       Yes            NaN          26-100  ...       Somewhat easy                        No                      No  Some of them  Some of them                      No                    No         Don't know              No      NaN
1255  2015-09-26 01:07:35   32    Male   United States    IL            No            Yes       Yes          Often          26-100  ...  Somewhat difficult                        No                      No  Some of them           Yes                      No                    No                Yes              No      NaN
1256  2015-11-07 12:36:58   34    male   United States    CA            No            Yes       Yes      Sometimes  More than 1000  ...  Somewhat difficult                       Yes                     Yes            No            No                      No                    No                 No              No      NaN
1257  2015-11-30 21:25:06   46       f   United States    NC            No             No        No            NaN         100-500  ...          Don't know                       Yes                      No            No            No                      No                    No                 No              No      NaN
1258  2016-02-01 23:04:31   25    Male   United States    IL            No            Yes       Yes      Sometimes          26-100  ...          Don't know                     Maybe                      No  Some of them            No                      No                    No         Don't know              No      NaN

[1259 rows x 27 columns]

In [3]:
print(survey.shape)

(1259, 27)

In [4]:
def clean_age(age):
    if age>=18 and age<=120:
        return round(age)
    else:
        return np.nan
survey['Age_clean'] = survey['Age'].apply(clean_age)

# Check out the new column and make sure it looks right

print("'Age'")
print("Minimum value: ", survey["Age_clean"].min())
print("Maximum value: ", survey["Age_clean"].max())
print("How many values are NaN?: ", pd.isnull(survey['Age_clean']).sum())
print("Frequency table for age_clean:")
survey["Age_clean"].value_counts().sort_index(0)

'Age'
Minimum value:  18.0
Maximum value:  72.0
How many values are NaN?:  8
Frequency table for age_clean:

18.0     7
19.0     9
20.0     6
21.0    16
22.0    21
23.0    51
24.0    46
25.0    61
26.0    75
27.0    71
28.0    68
29.0    85
30.0    63
31.0    67
32.0    82
33.0    70
34.0    65
35.0    55
36.0    37
37.0    43
38.0    39
39.0    33
40.0    33
41.0    21
42.0    20
43.0    28
44.0    11
45.0    12
46.0    12
47.0     2
48.0     6
49.0     4
50.0     6
51.0     5
53.0     1
54.0     3
55.0     3
56.0     4
57.0     3
58.0     1
60.0     2
61.0     1
62.0     1
65.0     1
72.0     1
Name: Age_clean, dtype: int64

In [5]:
survey = survey[survey['Age_clean'].notna()]

In [6]:
print(survey.shape)

(1251, 28)

In [7]:
survey['Age_clean'].mean()

32.07673860911271

In [8]:
print(survey.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1251 entries, 0 to 1258
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1251 non-null   object
 1   Age                        1251 non-null   int64
 2   Gender                     1251 non-null   object
 3   Country                    1251 non-null   object
 4   state                      738 non-null    object
 5   self_employed              1233 non-null   object
 6   family_history             1251 non-null   object
 7   treatment                  1251 non-null   object
 8   work_interfere             989 non-null    object
 9   no_employees               1251 non-null   object
 10  remote_work                1251 non-null   object
 11  tech_company               1251 non-null   object
 12  benefits                   1251 non-null   object
 13  care_options               1251 non-null   object
 14  wellness_program           1251 non-null   object
 15  seek_help                  1251 non-null   object
 16  anonymity                  1251 non-null   object
 17  leave                      1251 non-null   object
 18  mental_health_consequence  1251 non-null   object
 19  phys_health_consequence    1251 non-null   object
 20  coworkers                  1251 non-null   object
 21  supervisor                 1251 non-null   object
 22  mental_health_interview    1251 non-null   object
 23  phys_health_interview      1251 non-null   object
 24  mental_vs_physical         1251 non-null   object
 25  obs_consequence            1251 non-null   object
 26  comments                   161 non-null    object
 27  Age_clean                  1251 non-null   float64
dtypes: float64(1), int64(1), object(26)
memory usage: 283.4+ KB
None

In [9]:
#get rid of the variables "Timestamp",“comments”, “state”, dirty age
survey = survey.drop(['comments'], axis= 1)
survey = survey.drop(['state'], axis= 1)
survey = survey.drop(['Timestamp'], axis= 1)
survey = survey.drop(['Age'], axis= 1)


pd.set_option('display.max_columns', 100)
survey.head(5)

   Gender         Country self_employed family_history treatment work_interfere    no_employees remote_work tech_company    benefits care_options wellness_program   seek_help   anonymity               leave mental_health_consequence phys_health_consequence     coworkers supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence  Age_clean
0  Female   United States           NaN             No       Yes          Often            6-25          No          Yes         Yes     Not sure               No         Yes         Yes       Somewhat easy                        No                      No  Some of them        Yes                      No                 Maybe                Yes              No       37.0
1       M   United States           NaN             No        No         Rarely  More than 1000          No           No  Don't know           No       Don't know  Don't know  Don't know          Don't know                     Maybe                      No            No         No                      No                    No         Don't know              No       44.0
2    Male          Canada           NaN             No        No         Rarely            6-25          No          Yes          No           No               No          No  Don't know  Somewhat difficult                        No                      No           Yes        Yes                     Yes                   Yes                 No              No       32.0
3    Male  United Kingdom           NaN            Yes       Yes          Often          26-100          No          Yes          No          Yes               No          No          No  Somewhat difficult                       Yes                     Yes  Some of them         No                   Maybe                 Maybe                 No             Yes       31.0
4    Male   United States           NaN             No        No          Never         100-500         Yes          Yes         Yes           No       Don't know  Don't know  Don't know          Don't know                        No                      No  Some of them        Yes                     Yes                   Yes         Don't know              No       31.0

In [10]:
survey.rename(columns = {'Age_clean' : 'age'}, inplace = True)
survey

      Gender         Country self_employed family_history treatment work_interfere    no_employees remote_work tech_company    benefits care_options wellness_program   seek_help   anonymity               leave mental_health_consequence phys_health_consequence     coworkers    supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence   age
0     Female   United States           NaN             No       Yes          Often            6-25          No          Yes         Yes     Not sure               No         Yes         Yes       Somewhat easy                        No                      No  Some of them           Yes                      No                 Maybe                Yes              No  37.0
1          M   United States           NaN             No        No         Rarely  More than 1000          No           No  Don't know           No       Don't know  Don't know  Don't know          Don't know                     Maybe                      No            No            No                      No                    No         Don't know              No  44.0
2       Male          Canada           NaN             No        No         Rarely            6-25          No          Yes          No           No               No          No  Don't know  Somewhat difficult                        No                      No           Yes           Yes                     Yes                   Yes                 No              No  32.0
3       Male  United Kingdom           NaN            Yes       Yes          Often          26-100          No          Yes          No          Yes               No          No          No  Somewhat difficult                       Yes                     Yes  Some of them            No                   Maybe                 Maybe                 No             Yes  31.0
4       Male   United States           NaN             No        No          Never         100-500         Yes          Yes         Yes           No       Don't know  Don't know  Don't know          Don't know                        No                      No  Some of them           Yes                     Yes                   Yes         Don't know              No  31.0
...      ...             ...           ...            ...       ...            ...             ...         ...          ...         ...          ...              ...         ...         ...                 ...                       ...                     ...           ...           ...                     ...                   ...                ...             ...   ...
1254    male  United Kingdom            No             No       Yes            NaN          26-100          No          Yes          No           No               No          No  Don't know       Somewhat easy                        No                      No  Some of them  Some of them                      No                    No         Don't know              No  26.0
1255    Male   United States            No            Yes       Yes          Often          26-100         Yes          Yes         Yes          Yes               No          No         Yes  Somewhat difficult                        No                      No  Some of them           Yes                      No                    No                Yes              No  32.0
1256    male   United States            No            Yes       Yes      Sometimes  More than 1000          No          Yes         Yes          Yes               No          No  Don't know  Somewhat difficult                       Yes                     Yes            No            No                      No                    No                 No              No  34.0
1257       f   United States            No             No        No            NaN         100-500         Yes          Yes          No          Yes               No          No  Don't know          Don't know                       Yes                      No            No            No                      No                    No                 No              No  46.0
1258    Male   United States            No            Yes       Yes      Sometimes          26-100          No           No         Yes          Yes               No          No         Yes          Don't know                     Maybe                      No  Some of them            No                      No                    No         Don't know              No  25.0

[1251 rows x 24 columns]

In [11]:
print(survey.shape)

(1251, 24)

In [12]:
survey.age = survey.age.astype(int)

In [13]:
survey

      Gender         Country self_employed family_history treatment work_interfere    no_employees remote_work tech_company    benefits care_options wellness_program   seek_help   anonymity               leave mental_health_consequence phys_health_consequence     coworkers    supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence  age
0     Female   United States           NaN             No       Yes          Often            6-25          No          Yes         Yes     Not sure               No         Yes         Yes       Somewhat easy                        No                      No  Some of them           Yes                      No                 Maybe                Yes              No   37
1          M   United States           NaN             No        No         Rarely  More than 1000          No           No  Don't know           No       Don't know  Don't know  Don't know          Don't know                     Maybe                      No            No            No                      No                    No         Don't know              No   44
2       Male          Canada           NaN             No        No         Rarely            6-25          No          Yes          No           No               No          No  Don't know  Somewhat difficult                        No                      No           Yes           Yes                     Yes                   Yes                 No              No   32
3       Male  United Kingdom           NaN            Yes       Yes          Often          26-100          No          Yes          No          Yes               No          No          No  Somewhat difficult                       Yes                     Yes  Some of them            No                   Maybe                 Maybe                 No             Yes   31
4       Male   United States           NaN             No        No          Never         100-500         Yes          Yes         Yes           No       Don't know  Don't know  Don't know          Don't know                        No                      No  Some of them           Yes                     Yes                   Yes         Don't know              No   31
...      ...             ...           ...            ...       ...            ...             ...         ...          ...         ...          ...              ...         ...         ...                 ...                       ...                     ...           ...           ...                     ...                   ...                ...             ...  ...
1254    male  United Kingdom            No             No       Yes            NaN          26-100          No          Yes          No           No               No          No  Don't know       Somewhat easy                        No                      No  Some of them  Some of them                      No                    No         Don't know              No   26
1255    Male   United States            No            Yes       Yes          Often          26-100         Yes          Yes         Yes          Yes               No          No         Yes  Somewhat difficult                        No                      No  Some of them           Yes                      No                    No                Yes              No   32
1256    male   United States            No            Yes       Yes      Sometimes  More than 1000          No          Yes         Yes          Yes               No          No  Don't know  Somewhat difficult                       Yes                     Yes            No            No                      No                    No                 No              No   34
1257       f   United States            No             No        No            NaN         100-500         Yes          Yes          No          Yes               No          No  Don't know          Don't know                       Yes                      No            No            No                      No                    No                 No              No   46
1258    Male   United States            No            Yes       Yes      Sometimes          26-100          No           No         Yes          Yes               No          No         Yes          Don't know                     Maybe                      No  Some of them            No                      No                    No         Don't know              No   25

[1251 rows x 24 columns]

In [14]:
gender = survey['Gender'].str.lower()
gender = survey['Gender'].unique()

male_str = ["male", "m", "male-ish", "maile", "mal", "male (cis)", "make", "male ", "man","msle", "mail", "malr","cis man", "Cis Male", "cis male"]
nonbinary_str = ["trans-female", "something kinda male?", "queer/she/they", "non-binary","nah", "all", "enby", "fluid", "genderqueer", "androgyne", "agender", "male leaning androgynous", "guy (-ish) ^_^", "trans woman", "neuter", "female (trans)", "queer", "ostensibly male, unsure what that really means"]           
female_str = ["cis female", "f", "female", "woman",  "femake", "female ","cis-female/femme", "female (cis)", "femail"]

for (row, col) in survey.iterrows():

    if str.lower(col.Gender) in male_str:
        survey['Gender'].replace(to_replace=col.Gender, value='male', inplace=True)

    if str.lower(col.Gender) in female_str:
        survey['Gender'].replace(to_replace=col.Gender, value='female', inplace=True)

    if str.lower(col.Gender) in nonbinary_str:
        survey['Gender'].replace(to_replace=col.Gender, value='non-binary', inplace=True)

#Singkirkan omong kosong
stk_list = ['A little about you', 'p']
survey = survey[~survey['Gender'].isin(stk_list)]

print(survey['Gender'].unique())

['female' 'male' 'non-binary']

In [15]:
survey

      Gender         Country self_employed family_history treatment work_interfere    no_employees remote_work tech_company    benefits care_options wellness_program   seek_help   anonymity               leave mental_health_consequence phys_health_consequence     coworkers    supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence  age
0     female   United States           NaN             No       Yes          Often            6-25          No          Yes         Yes     Not sure               No         Yes         Yes       Somewhat easy                        No                      No  Some of them           Yes                      No                 Maybe                Yes              No   37
1       male   United States           NaN             No        No         Rarely  More than 1000          No           No  Don't know           No       Don't know  Don't know  Don't know          Don't know                     Maybe                      No            No            No                      No                    No         Don't know              No   44
2       male          Canada           NaN             No        No         Rarely            6-25          No          Yes          No           No               No          No  Don't know  Somewhat difficult                        No                      No           Yes           Yes                     Yes                   Yes                 No              No   32
3       male  United Kingdom           NaN            Yes       Yes          Often          26-100          No          Yes          No          Yes               No          No          No  Somewhat difficult                       Yes                     Yes  Some of them            No                   Maybe                 Maybe                 No             Yes   31
4       male   United States           NaN             No        No          Never         100-500         Yes          Yes         Yes           No       Don't know  Don't know  Don't know          Don't know                        No                      No  Some of them           Yes                     Yes                   Yes         Don't know              No   31
...      ...             ...           ...            ...       ...            ...             ...         ...          ...         ...          ...              ...         ...         ...                 ...                       ...                     ...           ...           ...                     ...                   ...                ...             ...  ...
1254    male  United Kingdom            No             No       Yes            NaN          26-100          No          Yes          No           No               No          No  Don't know       Somewhat easy                        No                      No  Some of them  Some of them                      No                    No         Don't know              No   26
1255    male   United States            No            Yes       Yes          Often          26-100         Yes          Yes         Yes          Yes               No          No         Yes  Somewhat difficult                        No                      No  Some of them           Yes                      No                    No                Yes              No   32
1256    male   United States            No            Yes       Yes      Sometimes  More than 1000          No          Yes         Yes          Yes               No          No  Don't know  Somewhat difficult                       Yes                     Yes            No            No                      No                    No                 No              No   34
1257  female   United States            No             No        No            NaN         100-500         Yes          Yes          No          Yes               No          No  Don't know          Don't know                       Yes                      No            No            No                      No                    No                 No              No   46
1258    male   United States            No            Yes       Yes      Sometimes          26-100          No           No         Yes          Yes               No          No         Yes          Don't know                     Maybe                      No  Some of them            No                      No                    No         Don't know              No   25

[1251 rows x 24 columns]

In [16]:
cols = list(survey.columns)
cols = [cols[-1]] + cols[:-1]
survey = survey[cols]
survey

      age  Gender         Country self_employed family_history treatment work_interfere    no_employees remote_work tech_company    benefits care_options wellness_program   seek_help   anonymity               leave mental_health_consequence phys_health_consequence     coworkers    supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence
0      37  female   United States           NaN             No       Yes          Often            6-25          No          Yes         Yes     Not sure               No         Yes         Yes       Somewhat easy                        No                      No  Some of them           Yes                      No                 Maybe                Yes              No
1      44    male   United States           NaN             No        No         Rarely  More than 1000          No           No  Don't know           No       Don't know  Don't know  Don't know          Don't know                     Maybe                      No            No            No                      No                    No         Don't know              No
2      32    male          Canada           NaN             No        No         Rarely            6-25          No          Yes          No           No               No          No  Don't know  Somewhat difficult                        No                      No           Yes           Yes                     Yes                   Yes                 No              No
3      31    male  United Kingdom           NaN            Yes       Yes          Often          26-100          No          Yes          No          Yes               No          No          No  Somewhat difficult                       Yes                     Yes  Some of them            No                   Maybe                 Maybe                 No             Yes
4      31    male   United States           NaN             No        No          Never         100-500         Yes          Yes         Yes           No       Don't know  Don't know  Don't know          Don't know                        No                      No  Some of them           Yes                     Yes                   Yes         Don't know              No
...   ...     ...             ...           ...            ...       ...            ...             ...         ...          ...         ...          ...              ...         ...         ...                 ...                       ...                     ...           ...           ...                     ...                   ...                ...             ...
1254   26    male  United Kingdom            No             No       Yes            NaN          26-100          No          Yes          No           No               No          No  Don't know       Somewhat easy                        No                      No  Some of them  Some of them                      No                    No         Don't know              No
1255   32    male   United States            No            Yes       Yes          Often          26-100         Yes          Yes         Yes          Yes               No          No         Yes  Somewhat difficult                        No                      No  Some of them           Yes                      No                    No                Yes              No
1256   34    male   United States            No            Yes       Yes      Sometimes  More than 1000          No          Yes         Yes          Yes               No          No  Don't know  Somewhat difficult                       Yes                     Yes            No            No                      No                    No                 No              No
1257   46  female   United States            No             No        No            NaN         100-500         Yes          Yes          No          Yes               No          No  Don't know          Don't know                       Yes                      No            No            No                      No                    No                 No              No
1258   25    male   United States            No            Yes       Yes      Sometimes          26-100          No           No         Yes          Yes               No          No         Yes          Don't know                     Maybe                      No  Some of them            No                      No                    No         Don't know              No

[1251 rows x 24 columns]

In [17]:
survey['age_range'] = pd.cut(survey['age'], [0,20,30,65,100], labels=["0-20", "21-30", "31-65", "66-100"], include_lowest=True)
survey

<ipython-input-17-569c7bd9eb7d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey['age_range'] = pd.cut(survey['age'], [0,20,30,65,100], labels=["0-20", "21-30", "31-65", "66-100"], include_lowest=True)

      age  Gender         Country self_employed family_history treatment work_interfere    no_employees remote_work tech_company    benefits care_options wellness_program   seek_help   anonymity               leave mental_health_consequence phys_health_consequence     coworkers    supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence age_range
0      37  female   United States           NaN             No       Yes          Often            6-25          No          Yes         Yes     Not sure               No         Yes         Yes       Somewhat easy                        No                      No  Some of them           Yes                      No                 Maybe                Yes              No     31-65
1      44    male   United States           NaN             No        No         Rarely  More than 1000          No           No  Don't know           No       Don't know  Don't know  Don't know          Don't know                     Maybe                      No            No            No                      No                    No         Don't know              No     31-65
2      32    male          Canada           NaN             No        No         Rarely            6-25          No          Yes          No           No               No          No  Don't know  Somewhat difficult                        No                      No           Yes           Yes                     Yes                   Yes                 No              No     31-65
3      31    male  United Kingdom           NaN            Yes       Yes          Often          26-100          No          Yes          No          Yes               No          No          No  Somewhat difficult                       Yes                     Yes  Some of them            No                   Maybe                 Maybe                 No             Yes     31-65
4      31    male   United States           NaN             No        No          Never         100-500         Yes          Yes         Yes           No       Don't know  Don't know  Don't know          Don't know                        No                      No  Some of them           Yes                     Yes                   Yes         Don't know              No     31-65
...   ...     ...             ...           ...            ...       ...            ...             ...         ...          ...         ...          ...              ...         ...         ...                 ...                       ...                     ...           ...           ...                     ...                   ...                ...             ...       ...
1254   26    male  United Kingdom            No             No       Yes            NaN          26-100          No          Yes          No           No               No          No  Don't know       Somewhat easy                        No                      No  Some of them  Some of them                      No                    No         Don't know              No     21-30
1255   32    male   United States            No            Yes       Yes          Often          26-100         Yes          Yes         Yes          Yes               No          No         Yes  Somewhat difficult                        No                      No  Some of them           Yes                      No                    No                Yes              No     31-65
1256   34    male   United States            No            Yes       Yes      Sometimes  More than 1000          No          Yes         Yes          Yes               No          No  Don't know  Somewhat difficult                       Yes                     Yes            No            No                      No                    No                 No              No     31-65
1257   46  female   United States            No             No        No            NaN         100-500         Yes          Yes          No          Yes               No          No  Don't know          Don't know                       Yes                      No            No            No                      No                    No                 No              No     31-65
1258   25    male   United States            No            Yes       Yes      Sometimes          26-100          No           No         Yes          Yes               No          No         Yes          Don't know                     Maybe                      No  Some of them            No                      No                    No         Don't know              No     21-30

[1251 rows x 25 columns]

In [18]:
survey.sort_values(by=['age'])

      age      Gender         Country self_employed family_history treatment work_interfere    no_employees remote_work tech_company    benefits care_options wellness_program   seek_help   anonymity               leave mental_health_consequence phys_health_consequence     coworkers    supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence age_range
482    18      female  United Kingdom            No            Yes       Yes      Sometimes             1-5         Yes          Yes  Don't know     Not sure       Don't know  Don't know  Don't know          Don't know                     Maybe                   Maybe  Some of them  Some of them                   Maybe                 Maybe         Don't know              No      0-20
93     18  non-binary          Russia            No             No        No            NaN          26-100         Yes          Yes         Yes          Yes               No          No         Yes       Somewhat easy                        No                      No           Yes           Yes                     Yes                   Yes         Don't know              No      0-20
287    18        male   United States            No             No        No          Never          26-100          No          Yes  Don't know     Not sure       Don't know  Don't know  Don't know           Very easy                        No                      No  Some of them  Some of them                      No                 Maybe                Yes              No      0-20
43     18        male     Netherlands            No             No        No          Often            6-25          No          Yes          No     Not sure               No          No  Don't know  Somewhat difficult                       Yes                   Maybe            No  Some of them                      No                    No                 No              No      0-20
118    18        male   United States            No             No       Yes         Rarely             1-5         Yes          Yes          No           No               No          No         Yes           Very easy                        No                      No  Some of them            No                      No                    No         Don't know              No      0-20
...   ...         ...             ...           ...            ...       ...            ...             ...         ...          ...         ...          ...              ...         ...         ...                 ...                       ...                     ...           ...           ...                     ...                   ...                ...             ...       ...
1236   60        male   United States            No             No       Yes          Often  More than 1000         Yes          Yes  Don't know           No              Yes  Don't know  Don't know       Somewhat easy                     Maybe                   Maybe  Some of them            No                      No                 Maybe         Don't know              No     31-65
952    61        male    South Africa           Yes             No       Yes      Sometimes             1-5         Yes          Yes          No           No               No          No  Don't know      Very difficult                       Yes                   Maybe  Some of them           Yes                      No                 Maybe                 No             Yes     31-65
520    62        male   United States            No             No        No          Never  More than 1000          No          Yes         Yes          Yes       Don't know         Yes  Don't know          Don't know                     Maybe                      No  Some of them           Yes                   Maybe                 Maybe                Yes              No     31-65
560    65        male   United States           Yes             No        No            NaN            6-25         Yes           No          No           No               No          No  Don't know           Very easy                     Maybe                      No  Some of them            No                      No                    No                Yes              No     31-65
1182   72      female   United States            No            Yes       Yes          Never        500-1000         Yes           No         Yes     Not sure       Don't know         Yes  Don't know       Somewhat easy                     Maybe                   Maybe  Some of them           Yes                      No                    No         Don't know             Yes    66-100

[1251 rows x 25 columns]

In [19]:
print(survey.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1251 entries, 0 to 1258
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        1251 non-null   int32
 1   Gender                     1251 non-null   object
 2   Country                    1251 non-null   object
 3   self_employed              1233 non-null   object
 4   family_history             1251 non-null   object
 5   treatment                  1251 non-null   object
 6   work_interfere             989 non-null    object
 7   no_employees               1251 non-null   object
 8   remote_work                1251 non-null   object
 9   tech_company               1251 non-null   object
 10  benefits                   1251 non-null   object
 11  care_options               1251 non-null   object
 12  wellness_program           1251 non-null   object
 13  seek_help                  1251 non-null   object
 14  anonymity                  1251 non-null   object
 15  leave                      1251 non-null   object
 16  mental_health_consequence  1251 non-null   object
 17  phys_health_consequence    1251 non-null   object
 18  coworkers                  1251 non-null   object
 19  supervisor                 1251 non-null   object
 20  mental_health_interview    1251 non-null   object
 21  phys_health_interview      1251 non-null   object
 22  mental_vs_physical         1251 non-null   object
 23  obs_consequence            1251 non-null   object
 24  age_range                  1251 non-null   category
dtypes: category(1), int32(1), object(23)
memory usage: 240.9+ KB
None

In [20]:
survey.work_interfere.isnull().sum()

262

In [21]:
#There are only 0.014% self-employed so let's change the NaN to NOT self-employed
survey['self_employed'] = survey['self_employed'].replace(np.nan, 'No')
print(survey['self_employed'].unique())

['No' 'Yes']

<ipython-input-21-dd66a0c76947>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey['self_employed'] = survey['self_employed'].replace(np.nan, 'No')

In [22]:
print(survey['work_interfere'].unique())

['Often' 'Rarely' 'Never' 'Sometimes' nan]

In [23]:
#There is only 0.20% of self work_interfere so let's change the NaN to "Don't know"
survey['work_interfere'] = survey['work_interfere'].replace(np.nan, 'Unknown' )
print(survey['work_interfere'].unique())

['Often' 'Rarely' 'Never' 'Sometimes' 'Unknown']

<ipython-input-23-c97fc4ab9746>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey['work_interfere'] = survey['work_interfere'].replace(np.nan, 'Unknown' )

In [24]:
print(survey.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1251 entries, 0 to 1258
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        1251 non-null   int32
 1   Gender                     1251 non-null   object
 2   Country                    1251 non-null   object
 3   self_employed              1251 non-null   object
 4   family_history             1251 non-null   object
 5   treatment                  1251 non-null   object
 6   work_interfere             1251 non-null   object
 7   no_employees               1251 non-null   object
 8   remote_work                1251 non-null   object
 9   tech_company               1251 non-null   object
 10  benefits                   1251 non-null   object
 11  care_options               1251 non-null   object
 12  wellness_program           1251 non-null   object
 13  seek_help                  1251 non-null   object
 14  anonymity                  1251 non-null   object
 15  leave                      1251 non-null   object
 16  mental_health_consequence  1251 non-null   object
 17  phys_health_consequence    1251 non-null   object
 18  coworkers                  1251 non-null   object
 19  supervisor                 1251 non-null   object
 20  mental_health_interview    1251 non-null   object
 21  phys_health_interview      1251 non-null   object
 22  mental_vs_physical         1251 non-null   object
 23  obs_consequence            1251 non-null   object
 24  age_range                  1251 non-null   category
dtypes: category(1), int32(1), object(23)
memory usage: 240.9+ KB
None

In [25]:
print(survey.shape)

(1251, 25)

In [26]:
survey

      age  Gender         Country self_employed family_history treatment work_interfere    no_employees remote_work tech_company    benefits care_options wellness_program   seek_help   anonymity               leave mental_health_consequence phys_health_consequence     coworkers    supervisor mental_health_interview phys_health_interview mental_vs_physical obs_consequence age_range
0      37  female   United States            No             No       Yes          Often            6-25          No          Yes         Yes     Not sure               No         Yes         Yes       Somewhat easy                        No                      No  Some of them           Yes                      No                 Maybe                Yes              No     31-65
1      44    male   United States            No             No        No         Rarely  More than 1000          No           No  Don't know           No       Don't know  Don't know  Don't know          Don't know                     Maybe                      No            No            No                      No                    No         Don't know              No     31-65
2      32    male          Canada            No             No        No         Rarely            6-25          No          Yes          No           No               No          No  Don't know  Somewhat difficult                        No                      No           Yes           Yes                     Yes                   Yes                 No              No     31-65
3      31    male  United Kingdom            No            Yes       Yes          Often          26-100          No          Yes          No          Yes               No          No          No  Somewhat difficult                       Yes                     Yes  Some of them            No                   Maybe                 Maybe                 No             Yes     31-65
4      31    male   United States            No             No        No          Never         100-500         Yes          Yes         Yes           No       Don't know  Don't know  Don't know          Don't know                        No                      No  Some of them           Yes                     Yes                   Yes         Don't know              No     31-65
...   ...     ...             ...           ...            ...       ...            ...             ...         ...          ...         ...          ...              ...         ...         ...                 ...                       ...                     ...           ...           ...                     ...                   ...                ...             ...       ...
1254   26    male  United Kingdom            No             No       Yes        Unknown          26-100          No          Yes          No           No               No          No  Don't know       Somewhat easy                        No                      No  Some of them  Some of them                      No                    No         Don't know              No     21-30
1255   32    male   United States            No            Yes       Yes          Often          26-100         Yes          Yes         Yes          Yes               No          No         Yes  Somewhat difficult                        No                      No  Some of them           Yes                      No                    No                Yes              No     31-65
1256   34    male   United States            No            Yes       Yes      Sometimes  More than 1000          No          Yes         Yes          Yes               No          No  Don't know  Somewhat difficult                       Yes                     Yes            No            No                      No                    No                 No              No     31-65
1257   46  female   United States            No             No        No        Unknown         100-500         Yes          Yes          No          Yes               No          No  Don't know          Don't know                       Yes                      No            No            No                      No                    No                 No              No     31-65
1258   25    male   United States            No            Yes       Yes      Sometimes          26-100          No           No         Yes          Yes               No          No         Yes          Don't know                     Maybe                      No  Some of them            No                      No                    No         Don't know              No     21-30

[1251 rows x 25 columns]

In [27]:

survey.to_csv('survey_clean.csv', index = False, header=True)